if(EXISTS "/home/aakennes/code/database/Database/build_rel/test/crash_test[1]_tests.cmake")
  include("/home/aakennes/code/database/Database/build_rel/test/crash_test[1]_tests.cmake")
else()
  add_test(crash_test_NOT_BUILT crash_test_NOT_BUILT)
endif()
