if(EXISTS "/home/aakennes/code/database/Database/build_rel/test/extendible_htable_test[1]_tests.cmake")
  include("/home/aakennes/code/database/Database/build_rel/test/extendible_htable_test[1]_tests.cmake")
else()
  add_test(extendible_htable_test_NOT_BUILT extendible_htable_test_NOT_BUILT)
endif()
