if(EXISTS "/home/aakennes/code/database/Database/build_rel/test/tuple_test[1]_tests.cmake")
  include("/home/aakennes/code/database/Database/build_rel/test/tuple_test[1]_tests.cmake")
else()
  add_test(tuple_test_NOT_BUILT tuple_test_NOT_BUILT)
endif()
